export type RootStackParamList = {
  App: undefined;
  Account: undefined;
  User: undefined;
  Diet: undefined;
  Diet7Days: undefined;
  CaloriesCalculation: undefined;
  About: undefined;
  Home: undefined;
  MealOfTheDay: undefined;
  Login: undefined;
  Registration: undefined;
  HomeStack: undefined;
  StackNavigator: undefined;
  MealOfTheDayNavigator: undefined;
  LoggedScreenTabNavigator: undefined;
  MealOfTheDayDrawerNavigation: undefined;
  Diet7DaysDrawerNavigation: undefined;
  DietDrawerNavigation: undefined;
  AccountStackNavigator: undefined;
  AboutStackNavigator: undefined;
  CaloriesCalculationStackNavigator: undefined;
  TabNavigation: undefined;
};